### ISSUE TITLE
Report if box is already filled

### ISSUE THREAD

**Issue by justgrimes** [emanuelfeld/tree-map#2]
It appears that a lot of the boxes have already been filled and the data is old. It would be nice if a person could also report or mark if a tree box has already been filled.

**Comment by emanuelfeld** [comment]
Like what? I'm taking in UFA's new dataset daily and subset according to their guidelines. I'd rather trust them than having the public decide. Street View is also not necessarily accurate, because it might point to the wrong side of the street, have outdated imagery, or the geocoordinates could be slightly off.

**Comment by justgrimes** [comment]
Fair points. I'm probably just misjudging the general quality and freshness of UFA's data.
